export const types = Object.freeze({
    // Sync
    STORE_START_FETCHING: 'STORE_START_FETCHING',
    STORE_STOP_FETCHING: 'STORE_STOP_FETCHING',
    STORE_FILL: 'STORE_FILL',
    STORE_SET_FETCHING_ERROR: 'STORE_SET_FETCHING_ERROR',
    // Async
    STORE_FETCH_ASYNC: 'STORE_FETCH_ASYNC',
});
